language: php

php:
  - hhvm
  - 5.6
  - 5.5
  - 5.4
  - 5.3

before_script:
  - composer self-update
  - composer install

script:
  - phpunit --coverage-text

matrix:
  allow_failures:
    - php: hhvm
